// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClG3KbyBtSPizuPNoXylG7Gpc8zhyexgo',
    appId: '1:240563199477:web:3498f791e15daa113254bc',
    messagingSenderId: '240563199477',
    projectId: 'todo-app-cd20f',
    authDomain: 'todo-app-cd20f.firebaseapp.com',
    storageBucket: 'todo-app-cd20f.appspot.com',
    measurementId: 'G-20NW0HNJW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBip0Pazr11b2jtSG-lU1crPNHTebn0ZlU',
    appId: '1:240563199477:android:3011f9d0330bd1a73254bc',
    messagingSenderId: '240563199477',
    projectId: 'todo-app-cd20f',
    storageBucket: 'todo-app-cd20f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEV9D0j2T2G0U0Dk2lZ1bXdCCWY6mIIkg',
    appId: '1:240563199477:ios:ebda21bd4c3cafec3254bc',
    messagingSenderId: '240563199477',
    projectId: 'todo-app-cd20f',
    storageBucket: 'todo-app-cd20f.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEV9D0j2T2G0U0Dk2lZ1bXdCCWY6mIIkg',
    appId: '1:240563199477:ios:ebda21bd4c3cafec3254bc',
    messagingSenderId: '240563199477',
    projectId: 'todo-app-cd20f',
    storageBucket: 'todo-app-cd20f.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClG3KbyBtSPizuPNoXylG7Gpc8zhyexgo',
    appId: '1:240563199477:web:2652f1d0644404143254bc',
    messagingSenderId: '240563199477',
    projectId: 'todo-app-cd20f',
    authDomain: 'todo-app-cd20f.firebaseapp.com',
    storageBucket: 'todo-app-cd20f.appspot.com',
    measurementId: 'G-1N7TYR56BY',
  );
}
